image: php:8.1

stages:
  - test
  - build

before_script:
  - apt-get update -qy
  - apt-get install -y unzip
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer install --no-interaction

test:
  stage: test
  script:
    - ./vendor/bin/phpunit

build:
    stage: build
    
    image: docker:20.10.16    
    
    services:
      - docker:20.10.16-dind
    
    variables:
      IMAGE_NAME : "tbonnal/supreme-enigma"
      IMAGE_TAG : "1.0"
      DOCKER_TLS_CERTDIR: "/certs"
          
    before_script:
      - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
    
    script:
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG
