version: "3.8"
services:
  # Mysql database container
  db:
    image: mysql
    container_name: supreme-enigma-db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  # Symfony apache project container
  app:
    build: ./
    container_name: supreme-enigma-app
    ports:
      - "8080:80"
    volumes:
      - ./vhost:/etc/apache2/sites-enabled
      - ../:/var/www/html
    restart: always

volumes:
  db-data:
